location-2/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\Email()]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    #[Assert\Length(min:6)]
    private $password;

    #[ORM\Column(type: 'string', length: 20)]
    #[Assert\Length(min:3)]
    private $pseudo;

    #[ORM\Column(type: 'string', length: 20)]
    #[Assert\Length(min:3)]
    private $nom;

    #[ORM\Column(type: 'string', length: 20)]
    #[Assert\Length(min:3)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 1)]
    #[Assert\Choice(callback:"getGenres")] // validation // enum()
    private $civilite;

    public function getGenres() : array{
        return ["m" , "f"];
    }

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    private $date_enregistrement;

    #[ORM\OneToMany(targetEntity:Commande::class, mappedBy:"user")]
    private $commandes;


    public function __construct()
    {
        $tz = new \DateTimeZone('Europe/Paris');
        $now = new \DateTime();
        $now->setTimezone($tz);	
        $this->setDateEnregistrement($now);
        $this->commandes = new ArrayCollection(); 
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    } 

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    
}

location-2/src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 200)]
    #[Assert\Length(min:3)]
    private $titre;

    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\Length(min:3)]
    private $modele;

    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\Length(min:3)]
    private $marque;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'string', length: 200)]
    #[Assert\Length(min:3)]
    private $photo;

    #[ORM\Column(type: 'integer')]
    #[Assert\GreaterThan(value:30)]
    private $prix_journalier;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    private $date_enregistrement; // create => constructeur 


    #[ORM\OneToMany(targetEntity:Commande::class , mappedBy:"vehicule")]
    private $commandes ;


    public function __construct()
    {
        $tz = new \DateTimeZone('Europe/Paris');
        $now = new \DateTime();
        $now->setTimezone($tz);	
        $this->setDateEnregistrement($now);
        $this->commandes = new ArrayCollection(); 
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): self
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setVehicule($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getVehicule() === $this) {
                $commande->setVehicule(null);
            }
        }

        return $this;
    }
}

location-2/templates/front/commande.html.twig
{% extends "base.html.twig" %}

{% block title %}Synthèse{% endblock %}


{% block body %}
<h2>Finaliser votre location</h2>
{{form(form)}}

{% endblock %}

location-2/templates/front/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Page d'accueil{% endblock %}


{% block body %}
<style>

.search_form{
    background: rgba(255,255,255,0.5);
    padding: 15px 30px 0 30px;
    margin-top: -110px ;  
}
</style>

<img src="/img/{{ asset("tableau-bord.jpg") }}" alt="" class="img-fluid mb-3" >
<div class="d-flex justify-content-center search">
        {{ form_start(form , { 'attr' : { 'class': 'search_form' } }) }}
            <div class="row align-items-end">
                <div class="col-5 form-floating">
                    {{ form_row(form.dt_debut ) }}
                </div>
                 <div class="col-5 form-floating">
                    {{ form_row(form.dt_fin) }}
                </div>
                <div class="col-2">
                    <input type="submit" class="btn btn-success mb-3">
                </div>
            </div>
        {{ form_end(form) }}
</div>

<main>
{%  for vehicule in vehicules %}
    <article class="row">
        <figure class="offset-3 col-3">
            <img src="/upload{{ asset(vehicule.photo)}}" alt="" class="img-fluid img-thumbnail border-dark">
        </figure>
        <div class="col-3">
            <h2 class="mb-0">{{vehicule.titre}}</h2>
            <p class="mb-0">{{vehicule.prixJournalier | deviseFr}}</p>
            <p>{{vehicule.description}}</p>
            <a href="{{ path("home_rent" , {"id" : vehicule.id }) }}" class="btn btn-primary">Louer </a>
        </div>
    </article>
{% else %}
    <p class="alert alert-danger">aucun véhicule enregistré pour le moment</p>
{% endfor %}
</main>


{% endblock %}

location-2/templates/front/inscription.html.twig
{% extends "base.html.twig" %}

{% block title %}Inscription{% endblock %}

{% block body %}
<h1>Inscription</h1>
<main class="row">
    <div class="offset-2 col-4">
        <h2 class="h3 mb-3 font-weight-normal">Créer un compte membre</h2>
        {{form_start(formInscription)}}
        {{form_end(formInscription)}}
    </div>
    <div class="col-4">
        <h2 class="h3 mb-3 font-weight-normal">Login</h2>
         {{form_start(formLogin)}}
        {{form_end(formLogin)}}
    </div>
</main>
{% endblock %}

location-2/templates/front/login.html.twig
{% extends "base.html.twig" %}

{% block titre %}
connexion
{% endblock %}

{% block body %}
<form method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputEmail">Email</label>
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
{% endblock %}

location-2/templates/front/registration.html.twig
{% extends "base.html.twig" %}

{% block title %}Inscription{% endblock %}

{% block body %}
<h1>Inscription</h1>
<main class="row">
    <div class="offset-2 col-4">
        <h2 class="h3 mb-3 font-weight-normal">Créer un compte membre</h2>
        {{form(formInscription)}}
    </div>
    <div class="col-4">
        {% include "commun/form-login.html.twig" %}
    </div>
</main>
{% endblock %}